### ISSUE TITLE
"at_ordered_refs" attribute not persisted when references set to another context

### ISSUE THREAD

**Issue by gbastien** [plone/Products.Archetypes#104]
Hi everybody,

we encountered a problem in https://github.com/plone/Products.Archetypes/blob/fc91db069f25c54cbd2538b08052e5375bbe201e/Products/Archetypes/Field.py#L2071

We have a code that set references on context and on other objects (kind of virtual folder with every elements referenced together).  When setting references on another object than context, the at_ordered_refs that is actually a dict and not a PersistentMapping is not persisted.  It's value is lost upon Zope restart.  And when it is empty, the get() will return nothing as it "filters" on order.

We had to add a _p_changed=True to the other objects where we set the references, I wondered if it should not be done after line #L2071, that solves our problem too.

What do you think about fixing it there?

Thank you,

Gauthier

**Comment by gbastien** [comment]
Hi @mauritsvanrees 

I poke you as you wrote the code ;-)

Actually the problem is that setting references (setRelatedItems) does not trigger the _p_changed attribute of an instance.

If I obj.setTitle('blabla'), then obj._p_changed=True, but if I obj.setRelatedItems([uid1, uid2]), obj._p_changed=False, this is not a problem most of times because references are stored in the reference_catalog and obj is not really changed except when using referencesSortable=True where the at_ordered_refs dict is changed on the instance.  First time you set it, it correctly turn _p_changed to True as the dict is added as an attribute to the instance, but second time, when the dict content is changed, _p_changed=False and changes are not persisted.

I would use a PersistentMapping so it solves the problem but then it needs a migration and that can be complicated, I do not know how to go.  But just managing the _p_changed=True manually is doing the job...

Thank you,

Gauthier

**Comment by mauritsvanrees** [comment]
I don't remember writing this part, although that does not say much. :-) Looks like I only did some pep8 cleanup.

But I agree with your logic. It seems good to solve this by setting `instance._p_changed = True`. I would be 👍 on that. Can you make a PR.

**Comment by tkimnguyen** [comment]
I don't see the problem in setting `_p_changed=True`. Is a migration necessary?

**Comment by mauritsvanrees** [comment]
No migration is necessary. A migration (possibly on-the-fly in the linked function) would only be needed when we move from the current simple dictionary to using a `PersistentMapping`.
There is no problem in setting `_p_changed=True`.  It is a fine solution.

**Comment by gbastien** [comment]
@tkimnguyen @mauritsvanrees 

we finally just added the _p_changed=True after at_ordered_refs dict is changed to make change persistent.  And it works.  Could there be releases with this, especially the 1.9.x branch?  If you do not have really time to do it, I can if you give me pypi rights, we are using zest.releaser...

Thank you!

Gauthier

**Comment by mauritsvanrees** [comment]
Fix released in 1.9.18 (Plone 4.3) and 1.10.19 (Plone 5.0) and 1.15.2 (Plone 5.1+).
Thanks.
