### ISSUE TITLE
Calendar ceiling reached for Plone 3.2.1

### ISSUE THREAD

**Issue by nikomds** [plone/Products.Archetypes#135]
Hello, I still maintain a Plone 3.2.1 instance.

The calendar widget will store dates beyond 2020/12/31, but will not show it, when editing again. This problem is the same as the shown in this [issue](https://github.com/plone/Products.Archetypes/issues/133) but for newer Plone version.

The problem is the ceiling in: Plone-3.2.1-py2.4.egg/Products/CMFPlone/skins/plone_scripts/date_components_support.py

I changed that file to:

PLONE_CEILING = DateTime(2500, 0) # 2499-12-31

But after buildout and reboot the machine, the problem is not solved.

How can I solve this problem?

**Comment by nikomds** [comment]
I found the problem was really in the file: plone.app.form-1.1.6-py2.4.egg/plone/app/form/widgets/datecomponents.py

Changing that file to:
PLONE_CEILING = DateTime(2500, 0) # 2499-12-31

And then making a buildout and rebooting the machine solved the problem!

**Comment by mauritsvanrees** [comment]
In November I [released `plone.app.form` 1.1.10](https://github.com/plone/Products.Archetypes/issues/133#issuecomment-720333776) with a fix. I am not sure if that version can be used in 3.2.1, but I guess so. Anyway, you seem to have found a solution for your system, so I close this issue.
