### ISSUE TITLE
TinyMCEWidget clobbers href paths

### ISSUE THREAD

**Issue by brownikowski** [plone/Products.Archetypes#73]
One can create a page using archetypes successfully, but editing and resaving that page clobbers all links. Symptoms: resolveuid href paths are translated into relative paths with an additional '../' prepended. Existing relative paths receive an additional '../' for each save.

The fix for the same issue in p.a.widgets appears to work here as well [https://github.com/plone/plone.app.widgets/commit/0064f0567f2dc7c90f38d56a42e181ebd60e267e](url)

**Comment by davisagli** [comment]
Fixed by https://github.com/plone/Products.Archetypes/pull/101
